[versions]
kotlin = "1.9.24"
ktor = "2.3.11"

[libraries]
library-jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
library-jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

library-ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
library-ktor-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

[plugins]
jetbrains-dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }