[versions]
kotlin = "2.0.0"
ktor = "2.3.11"

[libraries]
library-jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
library-jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

library-ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
library-ktor-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

plugin-sonatype = { module = "dev.g000sha256:sonatype-maven-central", version = "0.0.5" }

[plugins]
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }

jetbrains-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.16.2" }
jetbrains-kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }