name: Build

on:
  push:
    branches:
      - 'master'
      - 'release'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10
          cache-disabled: false
          cache-read-only: false

      - name: Assemble
        run: ./gradlew assemble

      - name: Binary compatibility validation
        run: ./gradlew apiCheck