name: Build

on:
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.3
          cache-disabled: false

      - name: Assemble
        run: ./gradlew assemble

      - name: Check binary compatibility
        run: ./gradlew apiCheck
