name: Dependency submission

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10
          cache-disabled: false
          cache-read-only: false

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4